# pubspec.yaml
name: my_wallet
description: "Simple wallet app for finance manage"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  collection: ^1.17.1
  fl_chart: ^0.65.0
  http: ^0.13.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/daily_json_fallback.js
  uses-material-design: true